# Command to test this localllu with nektos/act
# act -P ubuntu-latest=ubuntu-az --pull=false --secret-file .github/workflows/ga.secrets -e .github/workflows/event.json

name: Build and Push Container Image

on:
  push:
    branches:
      - main
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print Latest Commit SHA
        run: echo "Latest Commit SHA - ${{github.sha}}"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: exogeneralregistry.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build, Tag and Push the Image to Azure Container Registry
        id: build-image
        env:
          ACR_REGISTRY: exogeneralregistry.azurecr.io
          ACR_REPOSITORY: exo-web-app-v2
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64 -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
          docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy to Azure Web App Staging
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dev-exoai'
          slot-name: 'new-staging'
          images: 'exogeneralregistry.azurecr.io/exo-web-app-v2:${{ github.sha }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      #      - name: Deploy to Azure Web App Production
#        if: github.ref == 'refs/heads/release'
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'dev-exoai'
#          images: 'exogeneralregistry.azurecr.io/exo-web-app:${{ github.sha }}'

      #   TODO: Add publish to Slack #deployments channel
